#ifndef ERRORS_H
#define ERRORS_H

#include "types.h"

#define ERROR_MAX_LEN 256

enum ERROR_CODES{
	ERR_NONE,
	ERR_IO_CANT_READ_FILE,
	ERR_LEXE_MISSING_CLOSING_DOUBLE_QUOTE,
	ERR_LEXE_MISSING_CLOSING_SINGLE_QUOTE,
	ERR_LEXE_MISSING_CLOSING_BRACKET,
	ERR_LEXE_MISSING_CLOSING_PARENTHESIS,
	ERR_LEXE_MISSING_CLOSING_CURLY_BRACKET,
	ERR_LEXE_OUT_OF_MEMORY
};

void add_error(u32 err);

#endif